version: "3"
services:
  web:
    build:  .
    ports:
      - 5000:5000
    environment:
      - DOCKER=yes
    volumes:
      - /Apps/imagentexto
      - ./client:/app
  fastapi:
    build:  .
    ports:
      - 5050:5050
    environment:
      - DOCKER=yes
    volumes:
      - /Apps/myfastapiapp
      - ./client:/app2